### ISSUE TITLE
Removing Canbus Module

### ISSUE THREAD

**Issue by birkelbach** [makerplane/FIX-Gateway#12]
I seem to be reinventing the wheel with my canbus module.  There is a fairly mature called [python-can](https://bitbucket.org/hardbyte/python-can) that should do what we want.  I'll probably just build the can-fix interface on top of that with maybe some simulation capability for development and testing.  At least this way we can have access to all the hardware that python-can has access to and we don't have to fool with any of that.

**Comment by neil-d95** [comment]
Yeah I've had that happen to me. Where I was working on some module do 
another google search with an added spec and find a module that covers 
most of what I was wanting to do.

It's your call on the change but it make perfect sense to me. Plus we 
can commit issues we find back to them and save development time that we 
can shift elsewhere.


Neil
