### ISSUE TITLE
Unable to load daemon module

### ISSUE THREAD

**Issue by makerplane-jnicol** [makerplane/FIX-Gateway#88]
Try to launch gateway (fixgw.py) with latest master branch and it fails to launch.

Error message is:

**File "fixgw.py", line 20 in <module>
   import daemon
ImportError: No module named daemon**

**Comment by birkelbach** [comment]
Not really a bug.  Just need to install python-daemon package.  Will probably make this optional and only throw an error if the user tries to send the server to the background.
