### ISSUE TITLE
Database Locking

### ISSUE THREAD

**Issue by birkelbach** [makerplane/FIX-Gateway#9]
We've never implemented any locking on the database.  Most of the plugins operate in their own thread and all access the database at some level.  It seems to be working well enough.  I know in Python a lot of things are atomic that are not in other languages.  I can't really convince myself that we need it and it's seems to be working really well, but it goes against the grain on multithreaded programing to not lock common resources.  Comments?

**Comment by neil-d95** [comment]
I was talking with a coworker about this if we are talking about a multiple read, single write for a value. We might seen unusual thing in the data if it's reading while writing where as if we use a lock for the write process we can pull the most current data as well as mitigate odd data.

**Comment by birkelbach** [comment]
We are actually doing multiple writes and multiple reads (or at least it's possible to do so).  What I understand is that any read or write of a Python builtin type is guaranteed to be atomic.  Also the Python interpreter has the GIL so there is some locking going on inside the interpreter itself.  I don't know to what extent that helps.  My worry on locking is performance, but we may not have a performance problem.  Once we start throwing a bunch more data at this thing we'll see.  I should probably write some kind of test and see if I can make it fail.

**Comment by neil-d95** [comment]
Yeah that sounds like a this might need to stay out there till we get a 
handle on how the GIL locking holds up.

**Comment by birkelbach** [comment]
If I was seeing any problems or weird data I'd throw some locking at it in a heartbeat, but it all seems to be working fine.  My embedded and C programming experience says that this should not be... but Python is a different beast.
